### ISSUE TITLE
python train.py --theme=sample error

### ISSUE THREAD

**Issue by seossine** [daiz713/tfPhotoClassifier#2]
tfPhotoClassifierで自分の画像認識を作っています。
下のようにエラーが出ました。
どう解決できますか？

root@SEOPC:/mnt/c/Users/7020_64bit/AppData/Local/lxss/tfPhotoClassifier# python train.py --theme=sample
sample
['workspace/sample/tfrecords/sample-data0.tfrecords', 'workspace/sample/tfrecords/sample-data1.tfrecords', 'workspace/sample/tfrecords/sample-data2.tfrecords', 'workspace/sample/tfrecords/sample-data3.tfrecords']
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    train(tfrecord_file_paths=file_paths, theme=theme)
  File "train.py", line 55, in train
    images, labels = distorted_inputs(tfrecord_file_paths=tfrecord_file_paths)
  File "train.py", line 31, in distorted_inputs
    features = tf.parse_single_example(serialized_example, dense_keys=['label', 'image'], dense_types=[tf.int64, tf.string])
TypeError: parse_single_example() got an unexpected keyword argument 'dense_keys'
root@SEOPC:/mnt/c/Users/7020_64bit/AppData/Local/lxss/tfPhotoClassifier#

私のworkspaceは下のようです。
[sample.zip](https://github.com/daiz713/tfPhotoClassifier/files/401326/sample.zip)

train.pyの前までは完全にclearしました！
でも。。。train.pyで。。
ぜひ、助けてください。

**Comment by daiiz** [comment]
PythonとTensorFlowのバージョンを教えていただけますか？
Pythonのバージョンは

```
$ python --version
```

TensorFlowのバージョンは

```
$ pip freeze
```

を実行して `tensorflow==0.6.0`のように表示して確認できます！

tfPhotoClassifierは，現時点では
- Python 2.7系統
- TensorFlow 0.6.0 

のみを対象としています。

**Comment by seossine** [comment]
python 2.7.6
tensorflow 0.10.0rc0
です。

**Comment by daiiz** [comment]
ありがとうございます

TensorFlowのバージョンアップに伴う，TensorFlow APIの仕様変更が影響しているかもしれません．
調査しますのでお待ちください！

**Comment by daiiz** [comment]
作業完了しました。
masterブランチのコードは最新版TensorFlow 0.10.0rc0に対応しています！

**Comment by seossine** [comment]
ありがとうございます。
train.py実行に成功しました。
しかし、eval.py実行に何かメッセージがでました。
下のようです。
precision下にいろんなメッセージはエラーですか？あるいは、ただのメッセージですか？
聞きたいのです。

# python eval.py --theme=sample

2016-08-05 07:52:19.637637: precision @ 1 = 0.625
E tensorflow/core/client/tensor_c_api.cc:485] Enqueue operation was cancelled
         [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], _class=["loc:@shuffle_batch/random_shuffle_queue"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast_3)]]
E tensorflow/core/client/tensor_c_api.cc:485] Enqueue operation was cancelled
         [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueMany[Tcomponents=[DT_STRING], _class=["loc:@input_producer"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/RandomShuffle)]]

**Comment by daiiz** [comment]
precision以降のログは、ただのメッセージと考えて大丈夫です

**Comment by seossine** [comment]
ありがとうございます。
